version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - gocritic
    - revive
    - ineffassign
    - gosec

formatters:
  enable:
    - gofmt

settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: var-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-naming
      - name: var-declaration
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (net.Conn).Close
      - (*net.UDPConn).Close
      - (*net.UDPConn).Write
      - (*net.UDPConn).SetReadBuffer
      - (*net.UDPConn).SetReadDeadline
      - (*google.golang.org/grpc.ClientConn).Close

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - text: "Error return value of .*.Close"
      linters:
        - errcheck
    - text: "Error return value of `os.Remove`"
      linters:
        - errcheck
