// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 KeibiSoft S.R.L.

// A6 (swap-save-stamps 2026-10-01): a partial in-place write into a remote
// file that was never fully fetched. Before the fix the write made the file
// local as a whole, reads served the pre-allocated cache file, holes
// included, and Release announced the whole size; the owner then adopted
// zeros for every chunk the reader never fetched. Now the chunks a write
// touches are fetched first, a copy with chunks still missing stays a cache
// copy, and Release defers the announce to the fill.

package filesystem

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"sync/atomic"
	"testing"
	"time"

	"github.com/KeibiSoft/KeibiDrop/pkg/types"
	"github.com/stretchr/testify/require"
	winfuse "github.com/winfsp/cgofuse/fuse"
	"github.com/zeebo/xxh3"
)

// fillProvider serves a synthetic file on demand and through StreamFile, so
// the background fill can run in a unit test. Bytes are generated by offset.
type fillProvider struct {
	size        int64
	reads       atomic.Int64
	streamCalls atomic.Int64
}

func fillByte(off int64) byte { return byte(off%251) + 1 }

func (p *fillProvider) OpenRemoteFile(_ context.Context, _ uint64, _ string) (types.RemoteFileStream, error) {
	return &fillStream{p: p}, nil
}

func (p *fillProvider) StreamFile(_ context.Context, _ string, startOffset uint64) (types.StreamFileReceiver, error) {
	p.streamCalls.Add(1)
	return &fillReceiver{p: p, next: int64(startOffset)}, nil
}

type fillStream struct{ p *fillProvider }

func (s *fillStream) ReadAt(_ context.Context, offset int64, size int64) ([]byte, error) {
	s.p.reads.Add(1)
	if offset >= s.p.size {
		return []byte{}, nil
	}
	if offset+size > s.p.size {
		size = s.p.size - offset
	}
	out := make([]byte, size)
	for i := range out {
		out[i] = fillByte(offset + int64(i))
	}
	return out, nil
}
func (s *fillStream) Close() error { return nil }

type fillReceiver struct {
	p    *fillProvider
	next int64
}

func (r *fillReceiver) Recv() ([]byte, uint64, uint64, error) {
	const block = 4 * 1024 * 1024
	if r.next >= r.p.size {
		return nil, 0, uint64(r.p.size), io.EOF
	}
	n := min(int64(block), r.p.size-r.next)
	out := make([]byte, n)
	for i := range out {
		out[i] = fillByte(r.next + int64(i))
	}
	off := r.next
	r.next += n
	return out, uint64(off), uint64(r.p.size), nil
}

func newFillDir(t *testing.T, size int64) (*Dir, string, *fillProvider, func() []types.FileEvent) {
	t.Helper()
	saveDir := t.TempDir()
	d := newTestDir(saveDir)
	d.SetCtx(context.Background())
	prov := &fillProvider{size: size}
	d.SetStreamProvider(func() types.FileStreamProvider { return prov })
	var events []types.FileEvent
	evMu := make(chan struct{}, 1)
	evMu <- struct{}{}
	d.SetOnLocalChange(func(ev types.FileEvent) {
		<-evMu
		events = append(events, ev)
		evMu <- struct{}{}
	})
	snapshot := func() []types.FileEvent {
		<-evMu
		out := append([]types.FileEvent(nil), events...)
		evMu <- struct{}{}
		return out
	}
	require.NoError(t, d.AddRemoteFile(d.logger, "/big.bin", "big.bin", remoteStat(size, time.Now().Add(-time.Minute))))
	// The kernel looks the path up before the open: Getattr adopts the
	// announced entry into the tree.
	var st winfuse.Stat_t
	require.Equal(t, 0, d.Getattr("/big.bin", &st, 0))
	require.Equal(t, size, st.Size)
	return d, saveDir, prov, snapshot
}

func lastAdd(events []types.FileEvent, path string) *types.FileEvent {
	var out *types.FileEvent
	for i := range events {
		if events[i].Action == types.AddFile && events[i].Path == path {
			out = &events[i]
		}
	}
	return out
}

// A 4-byte patch at offset 0 of a never-fetched 2 MiB file. The chunks the
// write touches are fetched first; with the whole file inside one demand
// unit the copy is complete, so it is local from here on and Release
// announces at once. A read elsewhere serves the peer's bytes, not zeros.
func TestPartialWriteIntoUnfetchedRemoteFile_FetchesBeforeWriting(t *testing.T) {
	const size = int64(2 * 1048576)
	d, saveDir, prov, snapshot := newFillDir(t, size)

	fi := &winfuse.FileInfo_t{}
	fi.Flags = os.O_RDWR
	require.Equal(t, 0, d.OpenEx("/big.bin", fi))
	require.Equal(t, 4, d.Write("/big.bin", []byte("EDIT"), 0, fi.Fh))
	require.Positive(t, prov.reads.Load(), "the write must fetch the chunks it lands in")

	buf := make([]byte, 64)
	require.Equal(t, 64, d.Read("/big.bin", buf, 1048576, fi.Fh))
	want := make([]byte, 64)
	for i := range want {
		want[i] = fillByte(1048576 + int64(i))
	}
	require.Equal(t, want, buf, "a read outside the write must serve the peer's bytes")
	head := make([]byte, 8)
	require.Equal(t, 8, d.Read("/big.bin", head, 0, fi.Fh))
	require.Equal(t, append([]byte("EDIT"), fillByte(4), fillByte(5), fillByte(6), fillByte(7)), head,
		"the write must sit on top of the peer's bytes")

	require.Equal(t, 0, d.Release("/big.bin", fi.Fh))
	add := lastAdd(snapshot(), "/big.bin")
	require.NotNil(t, add, "a complete copy announces at Release")
	require.Equal(t, size, add.Attr.Size)

	data, err := os.ReadFile(filepath.Join(saveDir, "big.bin"))
	require.NoError(t, err)
	require.Equal(t, 0, bytes.Count(data[1048576:1048576+64], []byte{0}), "no hole on disk")
}

// A 1 MiB write at 1 MiB into a never-fetched 40 MiB file: only the units the
// write touches are fetched before it lands, the copy stays a cache copy,
// Release announces nothing, the background fill lands the rest without
// touching the written chunks, and the announce goes out when the fill is
// complete, with the whole file on disk.
func TestPartialWriteIntoUnfetchedRemoteFile_DefersAnnounceToFill(t *testing.T) {
	const size = int64(40 * 1048576)
	d, saveDir, prov, snapshot := newFillDir(t, size)

	fi := &winfuse.FileInfo_t{}
	fi.Flags = os.O_RDWR
	require.Equal(t, 0, d.OpenEx("/big.bin", fi))
	payload := bytes.Repeat([]byte{0xEE}, 1048576)
	require.Equal(t, len(payload), d.Write("/big.bin", payload, 1048576, fi.Fh))
	require.Positive(t, prov.reads.Load())

	d.AfmLock.RLock()
	f := d.AllFileMap["/big.bin"]
	d.AfmLock.RUnlock()
	require.NotNil(t, f)
	f.metaMu.RLock()
	stillCache := f.NotLocalSynced && !f.Bitmap.IsComplete()
	f.metaMu.RUnlock()
	require.True(t, stillCache, "a copy with chunks missing must stay a cache copy")

	require.Equal(t, 0, d.Release("/big.bin", fi.Fh))
	require.Nil(t, lastAdd(snapshot(), "/big.bin"), "Release must not announce a file with holes")

	require.Eventually(t, func() bool { return lastAdd(snapshot(), "/big.bin") != nil },
		30*time.Second, 20*time.Millisecond, "the fill must announce on completion")
	require.Positive(t, prov.streamCalls.Load(), "the fill runs through StreamFile")
	add := lastAdd(snapshot(), "/big.bin")
	require.Equal(t, size, add.Attr.Size)
	f.metaMu.RLock()
	require.True(t, f.Bitmap.IsComplete())
	require.False(t, f.NotLocalSynced)
	require.False(t, f.AnnounceAfterFill)
	f.metaMu.RUnlock()

	data, err := os.ReadFile(filepath.Join(saveDir, "big.bin"))
	require.NoError(t, err)
	require.Equal(t, size, int64(len(data)))
	require.Equal(t, payload, data[1048576:2*1048576], "the fill must not land the peer's bytes over the app's")
	for _, off := range []int64{0, 3 * 1048576, 20 * 1048576, size - 1} {
		require.Equal(t, fillByte(off), data[off], "byte at %d must be the peer's", off)
	}
	h, ok := f.Bitmap.Hash(2) // chunk 2 = [1 MiB, 1.5 MiB), rewritten by the app
	require.True(t, ok)
	require.Equal(t, xxh3.Hash(data[2*ChunkSize:3*ChunkSize]), h, "the stored fingerprint must describe the disk")
}

// A file truncated to zero holds no unfetched bytes: writes need no fill, the
// copy is local, and Release announces at once (the editor save pattern).
func TestTruncateToZeroThenWrite_NeedsNoFill(t *testing.T) {
	const size = int64(40 * 1048576)
	d, _, prov, snapshot := newFillDir(t, size)

	fi := &winfuse.FileInfo_t{}
	fi.Flags = os.O_RDWR
	require.Equal(t, 0, d.OpenEx("/big.bin", fi))
	require.Equal(t, 0, d.Truncate("/big.bin", 0, fi.Fh))
	require.Equal(t, 5, d.Write("/big.bin", []byte("fresh"), 0, fi.Fh))
	require.Zero(t, prov.reads.Load(), "a rewrite from zero fetches nothing")
	require.Equal(t, 0, d.Release("/big.bin", fi.Fh))
	add := lastAdd(snapshot(), "/big.bin")
	require.NotNil(t, add)
	require.Equal(t, int64(5), add.Attr.Size)
	require.Zero(t, prov.streamCalls.Load(), "no fill after a truncate to zero")
}

// A fetched range landing over a chunk that is already present leaves that
// chunk alone: it may hold a local write.
func TestMarkCached_NeverOverwritesPresentChunk(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "c.bin")
	size := int64(4 * ChunkSize)
	fh, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0o644)
	require.NoError(t, err)
	defer fh.Close()
	require.NoError(t, fh.Truncate(size))
	bm := NewChunkBitmap(size)
	local := bytes.Repeat([]byte{0xAB}, ChunkSize)
	_, err = fh.WriteAt(local, int64(ChunkSize))
	require.NoError(t, err)
	bm.Set(1)
	bm.SetHash(1, xxh3.Hash(local))

	fetched := bytes.Repeat([]byte{0x11}, int(size))
	n, err := markCached(fh, bm, fetched, 0, size)
	require.NoError(t, err)
	require.Equal(t, int(size)-ChunkSize, n, "the present chunk is skipped")
	require.True(t, bm.IsComplete())
	got := make([]byte, ChunkSize)
	_, err = fh.ReadAt(got, int64(ChunkSize))
	require.NoError(t, err)
	require.Equal(t, local, got, "the present chunk keeps the local bytes")
	h, ok := bm.Hash(1)
	require.True(t, ok)
	require.Equal(t, xxh3.Hash(local), h)
	_ = errors.New
}
