// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: keibidrop.proto

package keibidrop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyType int32

const (
	NotifyType_UNKNOWN     NotifyType = 0
	NotifyType_ADD_DIR     NotifyType = 1
	NotifyType_ADD_FILE    NotifyType = 2
	NotifyType_REMOVE_DIR  NotifyType = 3
	NotifyType_REMOVE_FILE NotifyType = 4
	NotifyType_EDIT_DIR    NotifyType = 5
	NotifyType_EDIT_FILE   NotifyType = 6
)

// Enum value maps for NotifyType.
var (
	NotifyType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADD_DIR",
		2: "ADD_FILE",
		3: "REMOVE_DIR",
		4: "REMOVE_FILE",
		5: "EDIT_DIR",
		6: "EDIT_FILE",
	}
	NotifyType_value = map[string]int32{
		"UNKNOWN":     0,
		"ADD_DIR":     1,
		"ADD_FILE":    2,
		"REMOVE_DIR":  3,
		"REMOVE_FILE": 4,
		"EDIT_DIR":    5,
		"EDIT_FILE":   6,
	}
)

func (x NotifyType) Enum() *NotifyType {
	p := new(NotifyType)
	*p = x
	return p
}

func (x NotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_keibidrop_proto_enumTypes[0].Descriptor()
}

func (NotifyType) Type() protoreflect.EnumType {
	return &file_keibidrop_proto_enumTypes[0]
}

func (x NotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyType.Descriptor instead.
func (NotifyType) EnumDescriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{0}
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Create        bool                   `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	Truncate      bool                   `protobuf:"varint,3,opt,name=truncate,proto3" json:"truncate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_keibidrop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenRequest) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *OpenRequest) GetTruncate() bool {
	if x != nil {
		return x.Truncate
	}
	return false
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty if success, because Go error culture
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_keibidrop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OpenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_keibidrop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint32                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_keibidrop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetBytesWritten() uint32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *WriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_keibidrop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *ReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_keibidrop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsyncRequest) Reset() {
	*x = FsyncRequest{}
	mi := &file_keibidrop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsyncRequest) ProtoMessage() {}

func (x *FsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsyncRequest.ProtoReflect.Descriptor instead.
func (*FsyncRequest) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{6}
}

func (x *FsyncRequest) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type FsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsyncResponse) Reset() {
	*x = FsyncResponse{}
	mi := &file_keibidrop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsyncResponse) ProtoMessage() {}

func (x *FsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsyncResponse.ProtoReflect.Descriptor instead.
func (*FsyncResponse) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{7}
}

func (x *FsyncResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_keibidrop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{8}
}

func (x *CloseRequest) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_keibidrop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{9}
}

func (x *CloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NotifyType             `protobuf:"varint,1,opt,name=type,proto3,enum=keibidrop.NotifyType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_keibidrop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyRequest) GetType() NotifyType {
	if x != nil {
		return x.Type
	}
	return NotifyType_UNKNOWN
}

func (x *NotifyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_keibidrop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keibidrop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_keibidrop_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_keibidrop_proto protoreflect.FileDescriptor

const file_keibidrop_proto_rawDesc = "" +
	"\n" +
	"\x0fkeibidrop.proto\x12\tkeibidrop\"U\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x12\x1a\n" +
	"\btruncate\x18\x03 \x01(\bR\btruncate\"<\n" +
	"\fOpenResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x04R\x06handle\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\fWriteRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x04R\x06handle\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"J\n" +
	"\rWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\rR\fbytesWritten\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\vReadRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x04R\x06handle\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"8\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\fFsyncRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x04R\x06handle\"%\n" +
	"\rFsyncResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"&\n" +
	"\fCloseRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x04R\x06handle\"%\n" +
	"\rCloseResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"N\n" +
	"\rNotifyRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.keibidrop.NotifyTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"(\n" +
	"\x0eNotifyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*r\n" +
	"\n" +
	"NotifyType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aADD_DIR\x10\x01\x12\f\n" +
	"\bADD_FILE\x10\x02\x12\x0e\n" +
	"\n" +
	"REMOVE_DIR\x10\x03\x12\x0f\n" +
	"\vREMOVE_FILE\x10\x04\x12\f\n" +
	"\bEDIT_DIR\x10\x05\x12\r\n" +
	"\tEDIT_FILE\x10\x062\xf3\x02\n" +
	"\fKeibiService\x127\n" +
	"\x04Open\x12\x16.keibidrop.OpenRequest\x1a\x17.keibidrop.OpenResponse\x12:\n" +
	"\x05Write\x12\x17.keibidrop.WriteRequest\x1a\x18.keibidrop.WriteResponse\x127\n" +
	"\x04Read\x12\x16.keibidrop.ReadRequest\x1a\x17.keibidrop.ReadResponse\x12:\n" +
	"\x05Fsync\x12\x17.keibidrop.FsyncRequest\x1a\x18.keibidrop.FsyncResponse\x12:\n" +
	"\x05Close\x12\x17.keibidrop.CloseRequest\x1a\x18.keibidrop.CloseResponse\x12=\n" +
	"\x06Notify\x12\x18.keibidrop.NotifyRequest\x1a\x19.keibidrop.NotifyResponseB8Z6github.com/KeibiSoft/KeibiDrop/grpc_bindings;keibidropb\x06proto3"

var (
	file_keibidrop_proto_rawDescOnce sync.Once
	file_keibidrop_proto_rawDescData []byte
)

func file_keibidrop_proto_rawDescGZIP() []byte {
	file_keibidrop_proto_rawDescOnce.Do(func() {
		file_keibidrop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keibidrop_proto_rawDesc), len(file_keibidrop_proto_rawDesc)))
	})
	return file_keibidrop_proto_rawDescData
}

var file_keibidrop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keibidrop_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_keibidrop_proto_goTypes = []any{
	(NotifyType)(0),        // 0: keibidrop.NotifyType
	(*OpenRequest)(nil),    // 1: keibidrop.OpenRequest
	(*OpenResponse)(nil),   // 2: keibidrop.OpenResponse
	(*WriteRequest)(nil),   // 3: keibidrop.WriteRequest
	(*WriteResponse)(nil),  // 4: keibidrop.WriteResponse
	(*ReadRequest)(nil),    // 5: keibidrop.ReadRequest
	(*ReadResponse)(nil),   // 6: keibidrop.ReadResponse
	(*FsyncRequest)(nil),   // 7: keibidrop.FsyncRequest
	(*FsyncResponse)(nil),  // 8: keibidrop.FsyncResponse
	(*CloseRequest)(nil),   // 9: keibidrop.CloseRequest
	(*CloseResponse)(nil),  // 10: keibidrop.CloseResponse
	(*NotifyRequest)(nil),  // 11: keibidrop.NotifyRequest
	(*NotifyResponse)(nil), // 12: keibidrop.NotifyResponse
}
var file_keibidrop_proto_depIdxs = []int32{
	0,  // 0: keibidrop.NotifyRequest.type:type_name -> keibidrop.NotifyType
	1,  // 1: keibidrop.KeibiService.Open:input_type -> keibidrop.OpenRequest
	3,  // 2: keibidrop.KeibiService.Write:input_type -> keibidrop.WriteRequest
	5,  // 3: keibidrop.KeibiService.Read:input_type -> keibidrop.ReadRequest
	7,  // 4: keibidrop.KeibiService.Fsync:input_type -> keibidrop.FsyncRequest
	9,  // 5: keibidrop.KeibiService.Close:input_type -> keibidrop.CloseRequest
	11, // 6: keibidrop.KeibiService.Notify:input_type -> keibidrop.NotifyRequest
	2,  // 7: keibidrop.KeibiService.Open:output_type -> keibidrop.OpenResponse
	4,  // 8: keibidrop.KeibiService.Write:output_type -> keibidrop.WriteResponse
	6,  // 9: keibidrop.KeibiService.Read:output_type -> keibidrop.ReadResponse
	8,  // 10: keibidrop.KeibiService.Fsync:output_type -> keibidrop.FsyncResponse
	10, // 11: keibidrop.KeibiService.Close:output_type -> keibidrop.CloseResponse
	12, // 12: keibidrop.KeibiService.Notify:output_type -> keibidrop.NotifyResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_keibidrop_proto_init() }
func file_keibidrop_proto_init() {
	if File_keibidrop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keibidrop_proto_rawDesc), len(file_keibidrop_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keibidrop_proto_goTypes,
		DependencyIndexes: file_keibidrop_proto_depIdxs,
		EnumInfos:         file_keibidrop_proto_enumTypes,
		MessageInfos:      file_keibidrop_proto_msgTypes,
	}.Build()
	File_keibidrop_proto = out.File
	file_keibidrop_proto_goTypes = nil
	file_keibidrop_proto_depIdxs = nil
}
